---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

verifier:
  name: inspec
  
platforms:
- name: windows2012r2
  driver:
    communicator: winrm
    gui: true
    box: opentable/win-2012r2-standard-amd64-nocm
    customize:
      memory: '2048'
      cpus: '2'
      vram: '32'
  transport: 
      name: winrm 
      max_threads: 6
suites:
- name: default
  run_list:
    - windows_logrotate::logrotate
    - log_rotate_test::create_old_log_files
    - windows_logrotate::delete_old_log_files
    - log_rotate_test::configure_chef_client_as_service
    - windows_logrotate::configure_chef_service_logfile
  attributes:
    windows_logrotate:
      log_type: daily_log
      days_to_keep_logs: 28
      log_file: c:\chef\log\client.log

